[package]
name = "display_adapter_attr"
version = "0.1.0"
authors = ["Zach Wolfe <zachrwolfe@me.com>"]
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

[lib]
name = "display_adapter_attr"
proc-macro = true